import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/modules/app/nav";
import { ClerkProvider } from "@clerk/nextjs";
import { Providers } from "@/modules/app/provider";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "PDFBridge",
  description: "Generated by create next app",
};

import { Toaster } from "sonner";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={`${inter.variable} antialiased`}>
          <Toaster position="top-right" richColors theme="dark" />
          <Navbar />
          <Providers>{children}</Providers>
        </body>
      </html>
    </ClerkProvider>
  );
}
