export { Hero } from "./hero";
export { SocialProof } from "./social-proof";
export { WhyPdfBridge } from "./why-pdfbridge";
export { HowItWorks } from "./how-it-works";
export { BuiltForDevelopers } from "./built-for-developers";
export { Pricing } from "./pricing";
export { FAQ } from "./faq";
export { CTA } from "./cta";
export { Footer } from "./footer";
